services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: api
    networks:
      - token-bucket

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    networks:
      - token-bucket

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - token-bucket

networks:
  token-bucket:

volumes:
  grafana-storage:
